Revert "Get Python files to pass pep8's tests."
This will fix issues while using migration script:
$ ~azat/git-multimail/git-multimail/migrate-mailhook-config --overwrite
Traceback (most recent call last):
  File "/home/azat/git-multimail/git-multimail/migrate-mailhook-config", line 271, in <module>
    main(sys.argv[1:])
  File "/home/azat/git-multimail/git-multimail/migrate-mailhook-config", line 268, in main
    migrate_config(strict=options.strict, retain=options.retain, overwrite=options.overwrite)
  File "/home/azat/git-multimail/git-multimail/migrate-mailhook-config", line 159, in migrate_config
    if not _check_old_config_exists(old):
  File "/home/azat/git-multimail/git-multimail/migrate-mailhook-config", line 66, in _check_old_config_exists
    if name in old:
TypeError: argument of type 'Config' is not iterable

This reverts commit 09d0d5b92203f019763e43cef1e57f76f117d2b4.

Conflicts:
	git-multimail/migrate-mailhook-config